stages:
    - deploy_alpha
deploy:
    stage:
        deploy_alpha
    only:
        - feature
    script:
        - sshpass -p "$ADMINPASS" rsync -avh * admin@13.114.119.107:/var/www/html/iscar_cp/
        - sshpass -p "$ADMINPASS" ssh admin@13.114.119.107 'sudo chown -R apache.apache /var/www/html/iscar_cp;sudo chmod -R 755 /var/www/html/iscar_cp;'
